[2024-12-29 12:56:59,401] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2024-12-29T12:56:57.520152+00:00 [queued]>
[2024-12-29 12:56:59,412] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2024-12-29T12:56:57.520152+00:00 [queued]>
[2024-12-29 12:56:59,413] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-12-29 12:56:59,413] {taskinstance.py:1096} INFO - Starting attempt 1 of 4
[2024-12-29 12:56:59,414] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-12-29 12:56:59,420] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2024-12-29T12:56:57.520152+00:00
[2024-12-29 12:56:59,424] {standard_task_runner.py:52} INFO - Started process 298 to run task
[2024-12-29 12:56:59,428] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2024-12-29T12:56:57.520152+00:00', '--job-id', '64', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpwr1vdgue', '--error-file', '/tmp/tmpmfr65uyi']
[2024-12-29 12:56:59,431] {standard_task_runner.py:77} INFO - Job 64: Subtask pyspark_train_classifier_model
[2024-12-29 12:56:59,468] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2024-12-29T12:56:57.520152+00:00 [running]> on host 5fe0c49fc1af
[2024-12-29 12:56:59,503] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2024-12-29T12:56:57.520152+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-29T12:56:57.520152+00:00
[2024-12-29 12:56:59,508] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-29 12:56:59,509] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   None//resources/train_spark_mllib_model.py   None/']
[2024-12-29 12:56:59,513] {subprocess.py:74} INFO - Output:
[2024-12-29 12:57:00,330] {subprocess.py:78} INFO - WARNING: An illegal reflective access operation has occurred
[2024-12-29 12:57:00,330] {subprocess.py:78} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2024-12-29 12:57:00,331] {subprocess.py:78} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2024-12-29 12:57:00,331] {subprocess.py:78} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2024-12-29 12:57:00,331] {subprocess.py:78} INFO - WARNING: All illegal access operations will be denied in a future release
[2024-12-29 12:57:00,530] {subprocess.py:78} INFO - 24/12/29 12:57:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-12-29 12:57:00,715] {subprocess.py:78} INFO - python: can't open file '/tmp/***tmpireht2nf/None/resources/train_spark_mllib_model.py': [Errno 2] No such file or directory
[2024-12-29 12:57:00,721] {subprocess.py:78} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2024-12-29 12:57:00,722] {subprocess.py:78} INFO - log4j:WARN Please initialize the log4j system properly.
[2024-12-29 12:57:00,722] {subprocess.py:78} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2024-12-29 12:57:00,750] {subprocess.py:82} INFO - Command exited with return code 2
[2024-12-29 12:57:00,759] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2024-12-29 12:57:00,761] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20241229T125657, start_date=20241229T125659, end_date=20241229T125700
[2024-12-29 12:57:00,805] {local_task_job.py:151} INFO - Task exited with return code 1
[2024-12-29 12:57:00,828] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
